import type { Shortcut, ShortcutAction } from './shortcut-types'

export const builtInActions: ShortcutAction[] = [
  { id: 'new-tab', name: 'New Tab', description: 'Open a new terminal tab' },
  {
    id: 'new-ssh',
    name: 'New SSH Connection',
    description: 'Create a new SSH connection',
  },
  {
    id: 'new-local',
    name: 'New Local Terminal',
    description: 'Open a new local terminal',
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    description: 'Open the command palette',
  },
  {
    id: 'toggle-sidebar',
    name: 'Toggle Sidebar',
    description: 'Show or hide the sidebar',
  },
  {
    id: 'split-horizontal',
    name: 'Split Horizontal',
    description: 'Split terminal horizontally',
  },
  {
    id: 'split-vertical',
    name: 'Split Vertical',
    description: 'Split terminal vertically',
  },
  { id: 'close-tab', name: 'Close Tab', description: 'Close the current tab' },
  { id: 'next-tab', name: 'Next Tab', description: 'Switch to the next tab' },
  {
    id: 'prev-tab',
    name: 'Previous Tab',
    description: 'Switch to the previous tab',
  },
  {
    id: 'reload-tab',
    name: 'Reload Tab',
    description: 'Reconnect the current session',
  },
  {
    id: 'clear-terminal',
    name: 'Clear Terminal',
    description: 'Clear terminal screen',
  },
  {
    id: 'search-terminal',
    name: 'Search in Terminal',
    description: 'Open terminal search',
  },
  { id: 'zoom-in', name: 'Zoom In', description: 'Increase font size' },
  { id: 'zoom-out', name: 'Zoom Out', description: 'Decrease font size' },
  {
    id: 'reset-zoom',
    name: 'Reset Zoom',
    description: 'Reset font size to default',
  },
]

export const defaultShortcuts: Shortcut[] = [
  {
    id: 'ctrl-t',
    name: 'New Tab',
    keys: ['Ctrl', 'T'],
    action: 'new-tab',
    enabled: true,
  },
  {
    id: 'ctrl-j',
    name: 'Command Palette',
    keys: ['Ctrl', 'J'],
    action: 'command-palette',
    enabled: true,
  },
  {
    id: 'ctrl-b',
    name: 'Toggle Sidebar',
    keys: ['Ctrl', 'B'],
    action: 'toggle-sidebar',
    enabled: true,
  },
  {
    id: 'ctrl-w',
    name: 'Close Tab',
    keys: ['Ctrl', 'W'],
    action: 'close-tab',
    enabled: true,
  },
  {
    id: 'ctrl-shift-t',
    name: 'New SSH Connection',
    keys: ['Ctrl', 'Shift', 'T'],
    action: 'new-ssh',
    enabled: true,
  },
  {
    id: 'ctrl-shift-n',
    name: 'New Local Terminal',
    keys: ['Ctrl', 'Shift', 'N'],
    action: 'new-local',
    enabled: true,
  },
  {
    id: 'ctrl-shift-h',
    name: 'Split Horizontal',
    keys: ['Ctrl', 'Shift', 'H'],
    action: 'split-horizontal',
    enabled: true,
  },
  {
    id: 'ctrl-shift-backslash',
    name: 'Split Vertical',
    keys: ['Ctrl', 'Shift', '\\'],
    action: 'split-vertical',
    enabled: true,
  },
  {
    id: 'ctrl-tab',
    name: 'Next Tab',
    keys: ['Ctrl', 'Tab'],
    action: 'next-tab',
    enabled: true,
  },
  {
    id: 'ctrl-shift-tab',
    name: 'Previous Tab',
    keys: ['Ctrl', 'Shift', 'Tab'],
    action: 'prev-tab',
    enabled: true,
  },
  {
    id: 'ctrl-k',
    name: 'Command Palette',
    keys: ['Ctrl', 'K'],
    action: 'command-palette',
    enabled: true,
    description: 'Open the command palette',
  },
  {
    id: 'ctrl-f',
    name: 'Search in Terminal',
    keys: ['Ctrl', 'F'],
    action: 'search-terminal',
    enabled: true,
  },
  {
    id: 'ctrl-l',
    name: 'Clear Terminal',
    keys: ['Ctrl', 'L'],
    action: 'clear-terminal',
    enabled: true,
  },
  {
    id: 'ctrl-equals',
    name: 'Zoom In',
    keys: ['Ctrl', '='],
    action: 'zoom-in',
    enabled: true,
  },
  {
    id: 'ctrl-minus',
    name: 'Zoom Out',
    keys: ['Ctrl', '-'],
    action: 'zoom-out',
    enabled: true,
  },
  {
    id: 'ctrl-0',
    name: 'Reset Zoom',
    keys: ['Ctrl', '0'],
    action: 'reset-zoom',
    enabled: true,
  },
]
