export const SYSTEM_SUBCOMMANDS: Record<string, string[]> = {
  cargo: [
    'build',
    'check',
    'test',
    'run',
    'bench',
    'doc',
    'publish',
    'update',
    'clean',
    'fmt',
    'clippy',
    'fix',
    'generate-lockfile',
    'metadata',
    'pkgid',
    'tree',
    'add',
    'remove',
    'update',
    'install',
    'uninstall',
    'search',
    'login',
    'logout',
    'owner',
    'yank',
    'search',
    'package',
  ],
  go: [
    'run',
    'build',
    'test',
    'get',
    'mod',
    'fmt',
    'vet',
    'install',
    'clean',
    'doc',
    'bug',
    'env',
    'fmt',
    'generate',
    'get',
    'help',
    'install',
    'list',
    'mod',
    'run',
    'test',
    'tool',
    'version',
    'vet',
    'work',
  ],
  python: [
    'install',
    'uninstall',
    'freeze',
    'list',
    'show',
    'check',
    'config',
    'debugpy',
    'pip',
    'python',
    'pyvenv',
  ],
  pip: [
    'install',
    'uninstall',
    'freeze',
    'list',
    'show',
    'check',
    'search',
    'install',
    'download',
    'cache',
    'index',
    'wheel',
  ],
  bun: [
    'install',
    'add',
    'remove',
    'update',
    'upgrade',
    'build',
    'dev',
    'start',
    'test',
    'create',
    'run',
    'exec',
    'x',
    'pm',
    'outdated',
    'link',
    'unlink',
    'login',
    'logout',
    'publish',
  ],
  ssh: ['-v', '-vv', '-vvv', '-L', '-R', '-D', '-N', '-f', '-g', '-o'],
  sudo: ['-u', '-s', '-i', '-n', '-l', '-k', '-e'],
  make: ['-f', '-n', '-j', '-k', '-s', '-B', '-C', '-I', '-W'],
  tmux: [
    'new',
    'kill',
    'ls',
    'detach',
    'attach',
    'send-keys',
    'split',
    'select',
    'resize',
    'swap',
    'rename',
    'kill-server',
  ],
  systemctl: [
    'start',
    'stop',
    'restart',
    'reload',
    'status',
    'enable',
    'disable',
    'daemon-reload',
    'is-active',
    'is-enabled',
    'mask',
    'unmask',
  ],
  ls: ['-a', '-l', '-h', '-R', '-t', '-S', '-r', '-d', '-1'],
  grep: ['-r', '-i', '-v', '-n', '-l', '-c', '-w', '-o', '-A', '-B', '-E'],
  find: [
    '-name',
    '-type',
    '-path',
    '-regex',
    '-mtime',
    '-size',
    '-exec',
    '-delete',
    '-print',
    '-depth',
    '-maxdepth',
    '-mindepth',
  ],
  chmod: ['+x', '-x', '777', '755', '644', '600', '400', '700'],
  chown: ['-R', '-v'],
  ps: ['aux', '-e', '-f', '-u'],
  kill: ['-9', '-15', '-l', '-s'],
}
